In [1]:
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

import warnings
warnings.filterwarnings('ignore')

In [2]:
driver = webdriver.Chrome(r"C:\Users\Lenovo\Desktop\DS\chromedriver.exe")
driver.get ('https://www.cars24.com/')
clo = driver.find_element_by_xpath('/html/body/div[1]/div[10]/div/div/h3/div')
clo.click()
for _ in range(100):
        driver.execute_script("window.scrollBy(0,10000)")

In [3]:
view = driver.find_element_by_xpath("//button[@class='btn _3BmFU AgO6q']")
view.click()

In [4]:
title = []
titl = driver.find_elements_by_xpath("//h2[@class='_3FpCg']")
for i in titl:
    tit = i.text
    title.append(tit)

kms = []
driven = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
for i in driven:
    dri = i.text
    kms.append(dri)

owner = []
onw = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
for i in onw:
    own = i.text
    owner.append(own)
    
fuel = []
fuele = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
for i in fuele:
    fue = i.text
    fuel.append(fue)
    
price = []
pric = driver.find_elements_by_xpath("//div[@class='_7udZZ']")
for i in pric:
    pri = i.text
    price.append(pri)
    
variant = []
var = driver.find_elements_by_xpath("//p[@class='cvakB']")
for i in var:
    vari = i.text
    variant.append(vari)

year = []
year = [i.split(' ')[0] for i in title]

brand = []
brand = [i.split(' ')[1] for i in title]

model = []
model = [i.split(' ')[2] for i in title]

df1 = pd.DataFrame({'Brand':brand,'Model':model,'Manufactured_year':year,'Running_kms':kms,'No_of_owner': owner,'Fuel_type':fuel,'Variant':variant,'Price':price,'Location':'New Delhi'})

In [7]:
loc = driver.find_element_by_xpath("//p[@class='_1V4-O']")
loc.click()

In [8]:
chenn = driver.find_element_by_xpath('/html/body/div[1]/div[10]/div/div/div/div[2]/ul/li[8]')
chenn.click()

In [9]:
view = driver.find_element_by_xpath("//button[@class='btn _3BmFU AgO6q']")
view.click()

In [10]:
titl = driver.find_elements_by_xpath("//h2[@class='_3FpCg']")
for i in titl:
    tit = i.text
    title.append(tit)

driven = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
for i in driven:
    dri = i.text
    kms.append(dri)

onw = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
for i in onw:
    own = i.text
    owner.append(own)
    
fuele = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
for i in fuele:
    fue = i.text
    fuel.append(fue)
    
pric = driver.find_elements_by_xpath("//div[@class='_7udZZ']")
for i in pric:
    pri = i.text
    price.append(pri)
    
var = driver.find_elements_by_xpath("//p[@class='cvakB']")
for i in var:
    vari = i.text
    variant.append(vari)

year = [i.split(' ')[0] for i in title]
brand = [i.split(' ')[1] for i in title]
model = [i.split(' ')[2] for i in title]

df2 = pd.DataFrame({'Brand':brand,'Model':model,'Manufactured_year':year,'Running_kms':kms,'No_of_owner': owner,'Fuel_type':fuel,'Variant':variant,'Price':price,'Location':'Chennai'})

In [11]:
loc = driver.find_element_by_xpath("//p[@class='_1V4-O']")
loc.click()

In [12]:
bang = driver.find_element_by_xpath('/html/body/div[1]/div[6]/div/div/div/div[2]/ul/li[6]/span/img')
bang.click()

In [13]:
titl = driver.find_elements_by_xpath("//h2[@class='_3FpCg']")
for i in titl:
    tit = i.text
    title.append(tit)

driven = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
for i in driven:
    dri = i.text
    kms.append(dri)

onw = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
for i in onw:
    own = i.text
    owner.append(own)
    
fuele = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
for i in fuele:
    fue = i.text
    fuel.append(fue)
    
pric = driver.find_elements_by_xpath("//div[@class='_7udZZ']")
for i in pric:
    pri = i.text
    price.append(pri)
    
var = driver.find_elements_by_xpath("//p[@class='cvakB']")
for i in var:
    vari = i.text
    variant.append(vari)

year = [i.split(' ')[0] for i in title]
brand = [i.split(' ')[1] for i in title]
model = [i.split(' ')[2] for i in title]

df3 = pd.DataFrame({'Brand':brand,'Model':model,'Manufactured_year':year,'Running_kms':kms,'No_of_owner': owner,'Fuel_type':fuel,'Variant':variant,'Price':price,'Location':'Bangalore'})

In [14]:
loc = driver.find_element_by_xpath("//p[@class='_1V4-O']")
loc.click()

In [15]:
hyde = driver.find_element_by_xpath('/html/body/div[1]/div[6]/div/div/div/div[2]/ul/li[7]/span/img')
hyde.click()

In [16]:
titl = driver.find_elements_by_xpath("//h2[@class='_3FpCg']")
for i in titl:
    tit = i.text
    title.append(tit)

driven = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
for i in driven:
    dri = i.text
    kms.append(dri)

onw = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
for i in onw:
    own = i.text
    owner.append(own)
    
fuele = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
for i in fuele:
    fue = i.text
    fuel.append(fue)
    
pric = driver.find_elements_by_xpath("//div[@class='_7udZZ']")
for i in pric:
    pri = i.text
    price.append(pri)
    
var = driver.find_elements_by_xpath("//p[@class='cvakB']")
for i in var:
    vari = i.text
    variant.append(vari)


year = [i.split(' ')[0] for i in title]
brand = [i.split(' ')[1] for i in title]
model = [i.split(' ')[2] for i in title]

df4 = pd.DataFrame({'Brand':brand,'Model':model,'Manufactured_year':year,'Running_kms':kms,'No_of_owner': owner,'Fuel_type':fuel,'Variant':variant,'Price':price,'Location':'Hyderabad'})

In [17]:
loc = driver.find_element_by_xpath("//p[@class='_1V4-O']")
loc.click()

In [18]:
kolk = driver.find_element_by_xpath('/html/body/div[1]/div[6]/div/div/div/div[2]/ul/li[9]/span/img')
kolk.click()

In [19]:
titl = driver.find_elements_by_xpath("//h2[@class='_3FpCg']")
for i in titl:
    tit = i.text
    title.append(tit)

driven = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
for i in driven:
    dri = i.text
    kms.append(dri)

onw = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
for i in onw:
    own = i.text
    owner.append(own)
    
fuele = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
for i in fuele:
    fue = i.text
    fuel.append(fue)
    
pric = driver.find_elements_by_xpath("//div[@class='_7udZZ']")
for i in pric:
    pri = i.text
    price.append(pri)
    
var = driver.find_elements_by_xpath("//p[@class='cvakB']")
for i in var:
    vari = i.text
    variant.append(vari)

year = [i.split(' ')[0] for i in title]
brand = [i.split(' ')[1] for i in title]
model = [i.split(' ')[2] for i in title]

df5 = pd.DataFrame({'Brand':brand,'Model':model,'Manufactured_year':year,'Running_kms':kms,'No_of_owner': owner,'Fuel_type':fuel,'Variant':variant,'Price':price,'Location':'Kolkata'})

In [20]:
loc = driver.find_element_by_xpath("//p[@class='_1V4-O']")
loc.click()

In [21]:
pune = driver.find_element_by_xpath('/html/body/div[1]/div[6]/div/div/div/div[2]/ul/li[5]/span/img')
pune.click()

In [22]:
titl = driver.find_elements_by_xpath("//h2[@class='_3FpCg']")
for i in titl:
    tit = i.text
    title.append(tit)

driven = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
for i in driven:
    dri = i.text
    kms.append(dri)

onw = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
for i in onw:
    own = i.text
    owner.append(own)
    
fuele = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
for i in fuele:
    fue = i.text
    fuel.append(fue)
    
pric = driver.find_elements_by_xpath("//div[@class='_7udZZ']")
for i in pric:
    pri = i.text
    price.append(pri)
    
var = driver.find_elements_by_xpath("//p[@class='cvakB']")
for i in var:
    vari = i.text
    variant.append(vari)

year = [i.split(' ')[0] for i in title]
brand = [i.split(' ')[1] for i in title]
model = [i.split(' ')[2] for i in title]

df6 = pd.DataFrame({'Brand':brand,'Model':model,'Manufactured_year':year,'Running_kms':kms,'No_of_owner': owner,'Fuel_type':fuel,'Variant':variant,'Price':price,'Location':'Pune'})

In [24]:
loc = driver.find_element_by_xpath("//p[@class='_1V4-O']")
loc.click()

In [25]:
mumb = driver.find_element_by_xpath('/html/body/div[1]/div[10]/div/div/div/div[2]/ul/li[4]/span/img')
mumb.click()

In [26]:
titl = driver.find_elements_by_xpath("//h2[@class='_3FpCg']")
for i in titl:
    tit = i.text
    title.append(tit)

driven = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
for i in driven:
    dri = i.text
    kms.append(dri)

onw = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
for i in onw:
    own = i.text
    owner.append(own)
    
fuele = driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
for i in fuele:
    fue = i.text
    fuel.append(fue)
    
pric = driver.find_elements_by_xpath("//div[@class='_7udZZ']")
for i in pric:
    pri = i.text
    price.append(pri)
    
var = driver.find_elements_by_xpath("//p[@class='cvakB']")
for i in var:
    vari = i.text
    variant.append(vari)

year = [i.split(' ')[0] for i in title]
brand = [i.split(' ')[1] for i in title]
model = [i.split(' ')[2] for i in title]

df7 = pd.DataFrame({'Brand':brand,'Model':model,'Manufactured_year':year,'Running_kms':kms,'No_of_owner': owner,'Fuel_type':fuel,'Variant':variant,'Price':price,'Location':'Mumbai'})

In [27]:
df = pd.concat([df1,df2,df3,df4,df5,df6,df7], axis = 0)

In [28]:
df

,Brand,Model,Manufactured_year,Running_kms,No_of_owner,Fuel_type,Variant,Price,Location
0,Maruti,Swift,2012,"1,29,639 km",1st Owner,Diesel,VDI Manual,"₹2,97,999",New Delhi
1,Maruti,Swift,2013,"76,795 km",1st Owner,Diesel,VDI BS IV Manual,"₹3,61,399",New Delhi
2,Maruti,Swift,2013,"66,341 km",1st Owner,Diesel,VDI BS IV Manual,"₹3,67,999",New Delhi
3,Maruti,Alto,2014,"40,562 km",1st Owner,Petrol,VXI Manual,"₹2,92,499",New Delhi
4,Maruti,Swift,2014,"56,467 km",1st Owner,Diesel,LDI BS IV Manual,"₹3,58,199",New Delhi
...,...,...,...,...,...,...,...,...,...
2618,Hyundai,Elite,2016,"65,640 km",1st Owner,Petrol,MAGNA 1.2 Manual,"₹5,09,999",Mumbai
2619,Ford,Ecosport,2017,"37,025 km",1st Owner,Petrol,1.5 TITANIUM TI VCT Manual,"₹7,10,999",Mumbai
2620,Honda,WR-V,2018,"41,342 km",1st Owner,Diesel,1.5 i-DTEC VX MT Manual,"₹8,37,899",Mumbai
2621,Honda,City,2016,"81,461 km",2nd Owner,Petrol,VX (O) PETROL Manual,"₹6,32,399",Mumbai
2622,Hyundai,i20,2013,"98,681 km",1st Owner,Diesel,ASTA 1.4 CRDI Manual,"₹4,35,399",Mumbai

In [29]:
df.to_csv('car_price_prediction.csv')

In [30]:
driver.close()