Q7: Go to the link - Set Price filter to “Rs. 6649 to Rs. 13099” , Color filter to “Black”, as shown in the below image.

In [1]:
import selenium
import pandas as pd
from selenium import webdriver

In [3]:
driver = webdriver.Chrome(r"C:\Users\Lenovo\Desktop\DS\chromedriver.exe")
driver.get('https://www.myntra.com/shoes')

<ipython-input-3-55f0531db345>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\Lenovo\Desktop\DS\chromedriver.exe")

In [4]:
price_filter = driver.find_element_by_xpath ('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label/div')
price_filter.click()

<ipython-input-4-84bf68e0293e>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  price_filter = driver.find_element_by_xpath ('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label/div')

In [5]:
color_filter = driver.find_element_by_xpath ('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/div')
color_filter.click()

<ipython-input-5-bbd6e3a8ce47>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  color_filter = driver.find_element_by_xpath ('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/div')

In [6]:
brand = []
description = []
price = []

In [12]:
brand_tag = driver.find_elements_by_class_name('product-brand')
for i in brand_tag:
    bran = i.text
    brand.append(bran)
brand

<ipython-input-12-ab46ee393cf5>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tag = driver.find_elements_by_class_name('product-brand')

['Nike',
 'Nike',
 'UNDER ARMOUR',
 'ASICS',
 'Puma',
 'Nike',
 'Tommy Hilfiger',
 'Saint G',
 'Hush Puppies',
 'Puma',
 'Puma',
 'ASICS',
 'Skechers',
 'Skechers',
 'Calvin Klein',
 'Hush Puppies',
 'Skechers',
 'Calvin Klein',
 'MANGO',
 'Tommy Hilfiger',
 'Puma',
 'Hush Puppies',
 'Hush Puppies',
 'ASICS',
 'Saint G',
 'ASICS',
 'ASICS',
 'UNDER ARMOUR',
 'Saint G',
 'Cole Haan',
 'Geox',
 'Saint G',
 'Cole Haan',
 'Tommy Hilfiger',
 'Hush Puppies',
 'Bugatti',
 'Calvin Klein',
 'Tommy Hilfiger',
 'Hush Puppies',
 'J.FONTINI',
 'Saint G',
 'MANGO',
 'Hush Puppies',
 'Hush Puppies',
 'Pavers England',
 'DAVINCHI',
 'DAVINCHI',
 'MANGO',
 'Tommy Hilfiger',
 'Pavers England',
 'Saint G']

In [13]:
desc = driver.find_elements_by_class_name('product-product')
for i in desc:
    des = i.text
    description.append(des)
description

<ipython-input-13-a67f5e253ee6>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  desc = driver.find_elements_by_class_name('product-product')

['Men Zoom Span 4 Running Shoes',
 'Men HOVR Apex 2 Training',
 'Men GEL-KAYANO 27 Shoes',
 'Men Electrify Nitro Running',
 "Men BlazerLow '77 Sneakers",
 'Women Leather Block Pumps',
 'Leather Block Heeled Boots',
 'Men Solid Leather Formal Slip-Ons',
 'Men Deviate Nitro Running Shoe',
 'Men Running Shoes',
 'Men Running Shoes',
 'Men Balance Anchor Walking',
 'Men Go Run Hyper Burst Running',
 'Men Textured Leather Sneaker',
 'Men Solid Leather Formal Slip-Ons',
 'Men Go Run Pure 2 Axis Running',
 'Men UV MONO Leather Sneakers',
 'Women WovenDesign Sports Shoes',
 'Men Lightweight Sneakers',
 'Women Eternity NITRO Shoes',
 'Men Solid Leather Formal Derbys',
 'Men Formal Derbys',
 'Men Black Running Sports Shoes',
 'Men Mid-Top Chelsea Boots',
 'Men Colourblocked PU Sneakers',
 'Skycourt Sneakers',
 'Women Charged Vantage ClrShft',
 'Women High-Top Heeled Boots',
 'Men Wingtip Oxford Sneakers',
 'Men Leather Mid-Top Flat Boots',
 'Leather Boots with Buckles',
 'Men GENERATION ZEROGRAND STITCHLITE',
 'Women ELEVATED Leather Sneaker',
 'Men Leather Slip-On Sneakers',
 'Leather Block Heeled Boots',
 'Men Solid Low Top LTH Sneakers',
 'Women Textured Pumps',
 'Men Leather Derbys',
 'Men Textured Leather Loafers',
 'Men Leather Chelsea Boots',
 'Women Mid Top Chunky Flat Boot',
 'Men Solid Formal Slip-Ons',
 'Men Solid Formal Leather Slip-Ons',
 'Men Textured Leather Formal Derbys',
 'Men Textured Formal Leather Loafers',
 'Men Textured Formal Leather Loafers',
 'Textured High-Top Flat Boots',
 'Women Hybrid Leather Sneakers',
 'Men Solid Leather Formal Loafers',
 'Women Leather Heeled Boots']

In [14]:
pric = driver.find_elements_by_class_name('product-price')
for i in pric:
    pri = i.text
    price.append(pri)
price

<ipython-input-14-5b47c9f1e909>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  pric = driver.find_elements_by_class_name('product-price')

['Rs. 7195',
 'Rs. 13999',
 'Rs. 11999Rs. 14999(20% OFF)',
 'Rs. 7499Rs. 9999(25% OFF)',
 'Rs. 7195',
 'Rs. 7999',
 'Rs. 7900Rs. 8900(Rs. 1000 OFF)',
 'Rs. 9999',
 'Rs. 11249Rs. 14999(25% OFF)',
 'Rs. 8449Rs. 12999(35% OFF)',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 8499',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 7499',
 'Rs. 8999',
 'Rs. 7191Rs. 7990(10% OFF)',
 'Rs. 7999',
 'Rs. 7799Rs. 12999(40% OFF)',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 9810Rs. 10900(Rs. 1090 OFF)',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 9800Rs. 13900(Rs. 4100 OFF)',
 'Rs. 12999',
 'Rs. 12999',
 'Rs. 8500Rs. 10500(Rs. 2000 OFF)',
 'Rs. 11999',
 'Rs. 7599',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 7599',
 'Rs. 7999',
 'Rs. 7990',
 'Rs. 10710Rs. 11900(Rs. 1190 OFF)',
 'Rs. 7191Rs. 7990(10% OFF)',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 8990',
 'Rs. 8990',
 'Rs. 7990',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 13410Rs. 14900(Rs. 1490 OFF)']

In [15]:
print(len(brand),len(description),len(price))

51 50 50

In [16]:
df = pd.DataFrame({'Brand':brand[:50],'Short Description':description,'Price':price})
df

,Brand,Short Description,Price
0,Nike,Men Zoom Span 4 Running Shoes,Rs. 7195
1,Nike,Men HOVR Apex 2 Training,Rs. 13999
2,UNDER ARMOUR,Men GEL-KAYANO 27 Shoes,Rs. 11999Rs. 14999(20% OFF)
3,ASICS,Men Electrify Nitro Running,Rs. 7499Rs. 9999(25% OFF)
4,Puma,Men BlazerLow '77 Sneakers,Rs. 7195
5,Nike,Women Leather Block Pumps,Rs. 7999
6,Tommy Hilfiger,Leather Block Heeled Boots,Rs. 7900Rs. 8900(Rs. 1000 OFF)
7,Saint G,Men Solid Leather Formal Slip-Ons,Rs. 9999
8,Hush Puppies,Men Deviate Nitro Running Shoe,Rs. 11249Rs. 14999(25% OFF)
9,Puma,Men Running Shoes,Rs. 8449Rs. 12999(35% OFF)
10,Puma,Men Running Shoes,Rs. 7999
11,ASICS,Men Balance Anchor Walking,Rs. 9999
12,Skechers,Men Go Run Hyper Burst Running,Rs. 8499
13,Skechers,Men Textured Leather Sneaker,Rs. 9999
14,Calvin Klein,Men Solid Leather Formal Slip-Ons,Rs. 8999
15,Hush Puppies,Men Go Run Pure 2 Axis Running,Rs. 7499
16,Skechers,Men UV MONO Leather Sneakers,Rs. 8999
17,Calvin Klein,Women WovenDesign Sports Shoes,Rs. 7191Rs. 7990(10% OFF)
18,MANGO,Men Lightweight Sneakers,Rs. 7999
19,Tommy Hilfiger,Women Eternity NITRO Shoes,Rs. 7799Rs. 12999(40% OFF)
20,Puma,Men Solid Leather Formal Derbys,Rs. 9999
21,Hush Puppies,Men Formal Derbys,Rs. 9999
22,Hush Puppies,Men Black Running Sports Shoes,Rs. 7999
23,ASICS,Men Mid-Top Chelsea Boots,Rs. 9810Rs. 10900(Rs. 1090 OFF)
24,Saint G,Men Colourblocked PU Sneakers,Rs. 9999
25,ASICS,Skycourt Sneakers,Rs. 7999
26,ASICS,Women Charged Vantage ClrShft,Rs. 7999
27,UNDER ARMOUR,Women High-Top Heeled Boots,Rs. 9800Rs. 13900(Rs. 4100 OFF)
28,Saint G,Men Wingtip Oxford Sneakers,Rs. 12999
29,Cole Haan,Men Leather Mid-Top Flat Boots,Rs. 12999
30,Geox,Leather Boots with Buckles,Rs. 8500Rs. 10500(Rs. 2000 OFF)
31,Saint G,Men GENERATION ZEROGRAND STITCHLITE,Rs. 11999
32,Cole Haan,Women ELEVATED Leather Sneaker,Rs. 7599
33,Tommy Hilfiger,Men Leather Slip-On Sneakers,Rs. 9999
34,Hush Puppies,Leather Block Heeled Boots,Rs. 9999
35,Bugatti,Men Solid Low Top LTH Sneakers,Rs. 8999
36,Calvin Klein,Women Textured Pumps,Rs. 7599
37,Tommy Hilfiger,Men Leather Derbys,Rs. 7999
38,Hush Puppies,Men Textured Leather Loafers,Rs. 7990
39,J.FONTINI,Men Leather Chelsea Boots,Rs. 10710Rs. 11900(Rs. 1190 OFF)
40,Saint G,Women Mid Top Chunky Flat Boot,Rs. 7191Rs. 7990(10% OFF)
41,MANGO,Men Solid Formal Slip-Ons,Rs. 9999
42,Hush Puppies,Men Solid Formal Leather Slip-Ons,Rs. 9999
43,Hush Puppies,Men Textured Leather Formal Derbys,Rs. 8999
44,Pavers England,Men Textured Formal Leather Loafers,Rs. 8990
45,DAVINCHI,Men Textured Formal Leather Loafers,Rs. 8990
46,DAVINCHI,Textured High-Top Flat Boots,Rs. 7990
47,MANGO,Women Hybrid Leather Sneakers,Rs. 7999
48,Tommy Hilfiger,Men Solid Leather Formal Loafers,Rs. 7999
49,Pavers England,Women Leather Heeled Boots,Rs. 13410Rs. 14900(Rs. 1490 OFF)

In [17]:
cli = driver.find_element_by_xpath ('/html/body/div[2]/div/div[1]/main/div[3]/div[2]/div/div[2]/section/div[2]/ul/li[3]/a')
cli.click()

<ipython-input-17-48dc5c7b25c8>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  cli = driver.find_element_by_xpath ('/html/body/div[2]/div/div[1]/main/div[3]/div[2]/div/div[2]/section/div[2]/ul/li[3]/a')

In [18]:
brand_tag = driver.find_elements_by_class_name('product-brand')
for i in brand_tag:
    bran = i.text
    brand.append(bran)
    
desc = driver.find_elements_by_class_name('product-product')
for i in desc:
    des = i.text
    description.append(des)

pric = driver.find_elements_by_class_name('product-price')
for i in pric:
    pri = i.text
    price.append(pri)
price

<ipython-input-18-df3ef41e726d>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tag = driver.find_elements_by_class_name('product-brand')
<ipython-input-18-df3ef41e726d>:6: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  desc = driver.find_elements_by_class_name('product-product')
<ipython-input-18-df3ef41e726d>:11: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  pric = driver.find_elements_by_class_name('product-price')

['Rs. 7195',
 'Rs. 13999',
 'Rs. 11999Rs. 14999(20% OFF)',
 'Rs. 7499Rs. 9999(25% OFF)',
 'Rs. 7195',
 'Rs. 7999',
 'Rs. 7900Rs. 8900(Rs. 1000 OFF)',
 'Rs. 9999',
 'Rs. 11249Rs. 14999(25% OFF)',
 'Rs. 8449Rs. 12999(35% OFF)',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 8499',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 7499',
 'Rs. 8999',
 'Rs. 7191Rs. 7990(10% OFF)',
 'Rs. 7999',
 'Rs. 7799Rs. 12999(40% OFF)',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 9810Rs. 10900(Rs. 1090 OFF)',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 9800Rs. 13900(Rs. 4100 OFF)',
 'Rs. 12999',
 'Rs. 12999',
 'Rs. 8500Rs. 10500(Rs. 2000 OFF)',
 'Rs. 11999',
 'Rs. 7599',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 7599',
 'Rs. 7999',
 'Rs. 7990',
 'Rs. 10710Rs. 11900(Rs. 1190 OFF)',
 'Rs. 7191Rs. 7990(10% OFF)',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 8990',
 'Rs. 8990',
 'Rs. 7990',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 13410Rs. 14900(Rs. 1490 OFF)',
 'Rs. 13410Rs. 14900(Rs. 1490 OFF)',
 'Rs. 11899Rs. 16999(30% OFF)',
 'Rs. 7599',
 'Rs. 12999',
 'Rs. 13999',
 'Rs. 12510Rs. 13900(Rs. 1390 OFF)',
 'Rs. 11900Rs. 13900(Rs. 2000 OFF)',
 'Rs. 11250Rs. 12500(Rs. 1250 OFF)',
 'Rs. 10500Rs. 10900(Rs. 400 OFF)',
 'Rs. 8999',
 'Rs. 8999',
 'Rs. 7499',
 'Rs. 7799Rs. 12999(40% OFF)',
 'Rs. 7499',
 'Rs. 9099Rs. 12999(30% OFF)',
 'Rs. 8999',
 'Rs. 7191Rs. 7990(10% OFF)',
 'Rs. 8999',
 'Rs. 8999',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 7990',
 'Rs. 8999',
 'Rs. 8990',
 'Rs. 9999',
 'Rs. 7699',
 'Rs. 11490',
 'Rs. 11999',
 'Rs. 7699Rs. 10999(30% OFF)',
 'Rs. 8990',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 8490',
 'Rs. 13495',
 'Rs. 9995',
 'Rs. 8990',
 'Rs. 11999',
 'Rs. 7990',
 'Rs. 7990',
 'Rs. 8990',
 'Rs. 11999',
 'Rs. 7990',
 'Rs. 8990',
 'Rs. 8990',
 'Rs. 7499',
 'Rs. 7499',
 'Rs. 9599Rs. 11999(20% OFF)',
 'Rs. 11999',
 'Rs. 11999']

In [19]:
print(len(brand),len(description),len(price))

101 100 100

In [20]:
df = pd.DataFrame({'Brand':brand[:100],'Short Description':description,'Price':price})
df

             Brand              Short Description                        Price
0             Nike  Men Zoom Span 4 Running Shoes                     Rs. 7195
1             Nike       Men HOVR Apex 2 Training                    Rs. 13999
2     UNDER ARMOUR        Men GEL-KAYANO 27 Shoes  Rs. 11999Rs. 14999(20% OFF)
3            ASICS    Men Electrify Nitro Running    Rs. 7499Rs. 9999(25% OFF)
4             Puma     Men BlazerLow '77 Sneakers                     Rs. 7195
..             ...                            ...                          ...
95        DAVINCHI     Men Leather Solid Sneakers                     Rs. 7499
96          Clarks      Men Leather Driving Shoes                     Rs. 7499
97  Pavers England   Men Supernova+ Running Shoes   Rs. 9599Rs. 11999(20% OFF)
98          ADIDAS      Men X9000L3 Running Shoes                    Rs. 11999
99          ADIDAS           Women Open Toe Flats                    Rs. 11999

[100 rows x 3 columns]

In [21]:
driver.close()