Q6: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the
search field.

In [1]:
import selenium
import pandas as pd
from selenium import webdriver

In [2]:
driver = webdriver.Chrome(r'C:\Users\Lenovo\Desktop\DS\chromedriver.exe')
driver.get ('https://www.flipkart.com/')

<ipython-input-2-52c15741ca28>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\Lenovo\Desktop\DS\chromedriver.exe')

In [3]:
searc_prod = driver.find_element_by_xpath ("//div[@class = '_3OO5Xc']/input")
searc_prod.send_keys ('sneakers')

<ipython-input-3-bf056d0a8e21>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  searc_prod = driver.find_element_by_xpath ("//div[@class = '_3OO5Xc']/input")

In [5]:
butt = driver.find_element_by_class_name ('L0Z3Pu')
butt.click()

<ipython-input-5-258021e74ac4>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  butt = driver.find_element_by_class_name ('L0Z3Pu')

In [6]:
brand = []
description = []
price = []
discount = []

In [7]:
brand_tag = driver.find_elements_by_class_name ('_2WkVRV')
for i in brand_tag:
    bran = i.text
    brand.append(bran)
brand

<ipython-input-7-663f15924a5b>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tag = driver.find_elements_by_class_name ('_2WkVRV')

['SHOEFLY',
 'Gzlizork',
 'RapidBox',
 'Chevit',
 'Numenzo',
 'Shoes Bank',
 'Magnolia',
 'Numenzo',
 'ganpati traders',
 'BIRDE',
 'Numenzo',
 'PUMA',
 'SCATCHITE',
 'Chevit',
 'Chevit',
 'Clymb',
 'T-ROCK',
 'URBANBOX',
 'PACIFIER',
 'Axter',
 'Clymb',
 'Robbie jones',
 'HOTSTYLE',
 'DURANE',
 'SPARX',
 'BRUTON',
 'RED TAPE',
 'NIKE',
 'ASIAN',
 'BIRDE',
 'Kraasa',
 'PUMA',
 'RODDICK SHOES',
 'Robbie jones',
 'BIRDE',
 'NIKE',
 'Chevit',
 'Numenzo',
 'PUMA',
 'NIKE']

In [8]:
descrip = driver.find_elements_by_class_name ('IRpwTa')
for i in descrip:
    des = i.text
    description.append(des)
description

<ipython-input-8-5fac35faa22e>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  descrip = driver.find_elements_by_class_name ('IRpwTa')

['Running Shoes For Men Sneakers For Men',
 'Walking || Dancing || Color Blocked Sneakers For Men',
 'Sneakers For Men',
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...',
 'White Sneaker For Men Sneakers For Men',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sports Running Shoes Sneakers For Men',
 '411 Casual Sneakers For Men',
 'Puma Smash v2 SL one8 Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Combo Pack of 4 Casual Sneakers With Sneakers For Men',
 'Combo Pack of 5 Casual Sneakers Sneakers For Men',
 'Mesh Sports/Walking Shoes/Outdoor Ultra Lightweight Run...',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 'New Collection of Combo Pack of 2 Stylish Shoes Sneaker...',
 'Sneakers For Men',
 'Casual Sneakers Black Shoes For Men Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'SM-322 Sneakers For Men',
 'Modern & Trendy Collection Combo Pack of 02 Shoes for M...',
 'Sneakers For Men',
 'Court Vapor Lite Hard Court Sneakers For Men',
 'Skypy-31 Walking Shoes,Training Shoes,Sneakers,Loafers,...',
 'Combo Pack of 2 Casual Shoes Sneakers For Men',
 'Shark-41 Sneakers For Men',
 'Shuffle Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Sneakers For Men',
 'Casual Shoes Sneakers For Men',
 'Court Legacy Suede Sneakers For Men',
 'Combo Pack of 3 Casual Shoes (Sneakers Shoes) Sneakers ...',
 'Numenzo Black Sneaker For Men Sneakers For Men',
 'Lazy Knit Slip On Sneakers For Men',
 'Court Vision Low Next Nature Sneakers For Men']

In [9]:
price_tag = driver.find_elements_by_class_name ('_30jeq3')
for i in price_tag:
    pri = i.text
    price.append(pri)
price

<ipython-input-9-6ecc79931378>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tag = driver.find_elements_by_class_name ('_30jeq3')

['₹259',
 '₹449',
 '₹680',
 '₹699',
 '₹479',
 '₹331',
 '₹398',
 '₹479',
 '₹145',
 '₹299',
 '₹499',
 '₹2,399',
 '₹398',
 '₹665',
 '₹899',
 '₹349',
 '₹379',
 '₹247',
 '₹499',
 '₹599',
 '₹649',
 '₹451',
 '₹198',
 '₹2,799',
 '₹849',
 '₹527',
 '₹1,319',
 '₹6,685',
 '₹439',
 '₹472',
 '₹499',
 '₹2,999',
 '₹499',
 '₹499',
 '₹348',
 '₹5,995',
 '₹745',
 '₹499',
 '₹1,382',
 '₹4,995',
 '₹1,319',
 '₹499',
 '₹665',
 '₹499',
 '₹398']

In [10]:
disco = driver.find_elements_by_class_name ('_3Ay6Sb')
for i in disco:
    disc = i.text
    discount.append(disc)
discount

<ipython-input-10-bc7c840da5b9>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  disco = driver.find_elements_by_class_name ('_3Ay6Sb')

['48% off',
 '55% off',
 '31% off',
 '56% off',
 '63% off',
 '66% off',
 '60% off',
 '63% off',
 '70% off',
 '40% off',
 '75% off',
 '40% off',
 '60% off',
 '66% off',
 '63% off',
 '65% off',
 '62% off',
 '75% off',
 '57% off',
 '39% off',
 '56% off',
 '54% off',
 '60% off',
 '15% off',
 '78% off',
 '70% off',
 '1% off',
 '45% off',
 '52% off',
 '50% off',
 '40% off',
 '50% off',
 '50% off',
 '65% off',
 '50% off',
 '61% off',
 '53% off',
 '70% off',
 '57% off',
 '66% off',
 '50% off',
 '60% off']

In [12]:
df = pd.DataFrame ({'Brand nmae':brand,'Product Description':description,'Price':price[:40],'Discount':discount[:40]})
df

,Brand nmae,Product Description,Price,Discount
0,SHOEFLY,Running Shoes For Men Sneakers For Men,₹259,48% off
1,Gzlizork,Walking || Dancing || Color Blocked Sneakers F...,₹449,55% off
2,RapidBox,Sneakers For Men,₹680,31% off
3,Chevit,Super Stylish & Trendy Combo Pack of 02 Pairs ...,₹699,56% off
4,Numenzo,White Sneaker For Men Sneakers For Men,₹479,63% off
5,Shoes Bank,White Sneaker For Men's/Boy's Sneakers For Men,₹331,66% off
6,Magnolia,Sneakers For Men,₹398,60% off
7,Numenzo,Sneakers For Men,₹479,63% off
8,ganpati traders,Sneakers For Men,₹145,70% off
9,BIRDE,Sports Running Shoes Sneakers For Men,₹299,40% off
10,Numenzo,411 Casual Sneakers For Men,₹499,75% off
11,PUMA,Puma Smash v2 SL one8 Sneakers For Men,"₹2,399",40% off
12,SCATCHITE,Sneakers Sneakers For Men,₹398,60% off
13,Chevit,Combo Pack of 4 Casual Sneakers With Sneakers ...,₹665,66% off
14,Chevit,Combo Pack of 5 Casual Sneakers Sneakers For Men,₹899,63% off
15,Clymb,Mesh Sports/Walking Shoes/Outdoor Ultra Lightw...,₹349,65% off
16,T-ROCK,Synthetic Leather Casual Partywear Wedding Sne...,₹379,62% off
17,URBANBOX,Sneakers Sneakers For Men,₹247,75% off
18,PACIFIER,Sneakers For Men,₹499,57% off
19,Axter,New Collection of Combo Pack of 2 Stylish Shoe...,₹599,39% off
20,Clymb,Sneakers For Men,₹649,56% off
21,Robbie jones,Casual Sneakers Black Shoes For Men Sneakers F...,₹451,54% off
22,HOTSTYLE,Sneakers For Men,₹198,60% off
23,DURANE,Sneakers For Men,"₹2,799",15% off
24,SPARX,SM-322 Sneakers For Men,₹849,78% off
25,BRUTON,Modern & Trendy Collection Combo Pack of 02 Sh...,₹527,70% off
26,RED TAPE,Sneakers For Men,"₹1,319",1% off
27,NIKE,Court Vapor Lite Hard Court Sneakers For Men,"₹6,685",45% off
28,ASIAN,"Skypy-31 Walking Shoes,Training Shoes,Sneakers...",₹439,52% off
29,BIRDE,Combo Pack of 2 Casual Shoes Sneakers For Men,₹472,50% off
30,Kraasa,Shark-41 Sneakers For Men,₹499,40% off
31,PUMA,Shuffle Sneakers For Men,"₹2,999",50% off
32,RODDICK SHOES,Fashion Outdoor Canvas Casual Light Weight Lac...,₹499,50% off
33,Robbie jones,Sneakers For Men,₹499,65% off
34,BIRDE,Casual Shoes Sneakers For Men,₹348,50% off
35,NIKE,Court Legacy Suede Sneakers For Men,"₹5,995",61% off
36,Chevit,Combo Pack of 3 Casual Shoes (Sneakers Shoes) ...,₹745,53% off
37,Numenzo,Numenzo Black Sneaker For Men Sneakers For Men,₹499,70% off
38,PUMA,Lazy Knit Slip On Sneakers For Men,"₹1,382",57% off
39,NIKE,Court Vision Low Next Nature Sneakers For Men,"₹4,995",66% off

In [13]:
butt_2 = driver.find_element_by_xpath ("/html/body/div[1]/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[2]")
butt_2.click()

<ipython-input-13-9793b4b19316>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  butt_2 = driver.find_element_by_xpath ("/html/body/div[1]/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[2]")

In [14]:
brand_tag = driver.find_elements_by_class_name ('_2WkVRV')
for i in brand_tag:
    bran = i.text
    brand.append(bran)
descrip = driver.find_elements_by_class_name ('IRpwTa')
for i in descrip:
    des = i.text
    description.append(des)
price_tag = driver.find_elements_by_class_name ('_30jeq3')
for i in price_tag:
    pri = i.text
    price.append(pri)
disco = driver.find_elements_by_class_name ('_3Ay6Sb')
for i in disco:
    disc = i.text
    discount.append(disc)

<ipython-input-14-8e49f4a77829>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tag = driver.find_elements_by_class_name ('_2WkVRV')
<ipython-input-14-8e49f4a77829>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  descrip = driver.find_elements_by_class_name ('IRpwTa')
<ipython-input-14-8e49f4a77829>:9: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tag = driver.find_elements_by_class_name ('_30jeq3')
<ipython-input-14-8e49f4a77829>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  disco = driver.find_elements_by_class_name ('_3Ay6Sb')

In [16]:
df = pd.DataFrame ({'Brand nmae':brand,'Product Description':description,'Price':price[:80],'Discount':discount[:80]})
df

,Brand nmae,Product Description,Price,Discount
0,SHOEFLY,Running Shoes For Men Sneakers For Men,₹259,48% off
1,Gzlizork,Walking || Dancing || Color Blocked Sneakers F...,₹449,55% off
2,RapidBox,Sneakers For Men,₹680,31% off
3,Chevit,Super Stylish & Trendy Combo Pack of 02 Pairs ...,₹699,56% off
4,Numenzo,White Sneaker For Men Sneakers For Men,₹479,63% off
...,...,...,...,...
75,sixXplus,Sneakers for men ( blue 06) Sneakers For Men,"₹2,199",54% off
76,CALCADOS,Modern Trendy Shoes Combo pack of 4 Sneakers F...,₹499,65% off
77,Trendmode,Sneakers For Men,₹459,70% off
78,TR,Sneakers For Men,₹499,50% off
79,sixXplus,Sneakers for men ( beige 06) Sneakers For Men,₹499,70% off

In [17]:
butt_3 = driver.find_element_by_xpath ("/html/body/div[1]/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[3]")
butt_3.click()

<ipython-input-17-219c8597df67>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  butt_3 = driver.find_element_by_xpath ("/html/body/div[1]/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[3]")

In [18]:
brand_tag = driver.find_elements_by_class_name ('_2WkVRV')
for i in brand_tag:
    bran = i.text
    brand.append(bran)
descrip = driver.find_elements_by_class_name ('IRpwTa')
for i in descrip:
    des = i.text
    description.append(des)
price_tag = driver.find_elements_by_class_name ('_30jeq3')
for i in price_tag:
    pri = i.text
    price.append(pri)
disco = driver.find_elements_by_class_name ('_3Ay6Sb')
for i in disco:
    disc = i.text
    discount.append(disc)

<ipython-input-18-8e49f4a77829>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tag = driver.find_elements_by_class_name ('_2WkVRV')
<ipython-input-18-8e49f4a77829>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  descrip = driver.find_elements_by_class_name ('IRpwTa')
<ipython-input-18-8e49f4a77829>:9: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tag = driver.find_elements_by_class_name ('_30jeq3')
<ipython-input-18-8e49f4a77829>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  disco = driver.find_elements_by_class_name ('_3Ay6Sb')

In [20]:
df = pd.DataFrame ({'Brand nmae':brand[:100],'Product Description':description[:100],'Price':price[:100],'Discount':discount[:100]})
df

,Brand nmae,Product Description,Price,Discount
0,SHOEFLY,Running Shoes For Men Sneakers For Men,₹259,48% off
1,Gzlizork,Walking || Dancing || Color Blocked Sneakers F...,₹449,55% off
2,RapidBox,Sneakers For Men,₹680,31% off
3,Chevit,Super Stylish & Trendy Combo Pack of 02 Pairs ...,₹699,56% off
4,Numenzo,White Sneaker For Men Sneakers For Men,₹479,63% off
...,...,...,...,...
95,NIKE,Sneakers For Men,₹498,46% off
96,RODDICK SHOES,Fashion Outdoor Canvas Casual Light Weight Lac...,₹689,65% off
97,Clymb,Sneakers For Men,₹418,19% off
98,URBANBOX,STYLISH-WHITE-9 Sneakers For Men,₹299,50% off
99,Clymb,Mesh Running/Walking Shoes/Outdoor Ultra Light...,₹499,56% off

In [21]:
driver.close()